# Default values for spin-acme.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: docker.io/dingpf/acme
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: latest

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""


podAnnotations: {}
podLabels: {}

podSecurityContext:
  fsGroup: <gid>

securityContext:
  capabilities:
     drop:
     - ALL
  readOnlyRootFilesystem: false
  runAsNonRoot: true
  runAsUser: <uid>

service:
  type: ClusterIP
  port: 8080

ingress:
  name: cert
  enabled: true
  className: nginx
  hosts:
    - host: <domain>
      paths:
        - path: /
          pathType: Prefix
  tls:
   - hosts:
      - <domain>

# concatenate the list .ingress.hosts.host into ":" separated string
domain: <domain>

email: <email>

cluster: development.svc.spin.nersc.org

webServer:
  webrootPath: "/www"
  existing: true
  deploymentName: <existing-websrv>
  claimName: <pvc-existing-webroot>

kubeconfig:
  secretName: kubeconfig

cert:
  secretName: tls-cert

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
